# Generated by Django 6.0.5 on 2026-05-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_playlist_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_comments', to='core.track'),
        ),
    ]
